[tool.black]
line-length = 79

[tool.isort]
force_single_line = true # Force from .. import to be 1 per line, minimizing changes at time of implementation
known_first_party = "ansible_navigator, key_value_store" # No effect at implementation, here anticipating future benefit
lines_after_imports = 2 # Ensures consistency for cases when there's variable vs function/class definitions after imports
lines_between_types = 1 # Separate import/from with 1 line, minimizing changes at time of implementation
no_lines_before = "LOCALFOLDER" # Keeps local imports bundled with first-party
profile = "black" # Avoid conflict with black
skip_glob = [
    "tests/fixtures/common/collections*"
] # Skip ansible content due to ansible-test sanity ruleset

[tool.pylint]

[tool.pylint.format]
max-line-length = 100

[tool.pytest.ini_options]
addopts = "-s --profile-svg"
testpaths = ["tests"]
filterwarnings = [
    'ignore:AnsibleCollectionFinder has already been configured',
    'ignore:_AnsibleCollectionFinder.find_spec().*',
]
markers = ["serial: Run this test serially via filelock."]
